import Link from "next/link";

import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";

const public_sans = Public_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={public_sans.className}>
        <ul>
          <li>
            <Link href="/overview">Overview</Link>
            <Link href="/transactions">Transactions</Link>
            <Link href="/budgets">Budgets</Link>
            <Link href="/pots">Pots</Link>
            <Link href="/bills">Recurring Bills</Link>
          </li>
        </ul>
        {children}
      </body>
    </html>
  );
}
